# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './window_ui/edit_section.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 352)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.hide_tool_button = QtWidgets.QToolButton(Form)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.hide_tool_button.setFont(font)
        self.hide_tool_button.setStyleSheet("QToolButton {\n"
"    border-radius: 8px;\n"
"    border: 2px solid red;\n"
"      color: black;\n"
"      padding: 20px;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      font-size: 16px;\n"
"      margin: 0px 0px;\n"
"}")
        self.hide_tool_button.setIconSize(QtCore.QSize(18, 18))
        self.hide_tool_button.setObjectName("hide_tool_button")
        self.horizontalLayout_5.addWidget(self.hide_tool_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.data_layout = QtWidgets.QFormLayout()
        self.data_layout.setObjectName("data_layout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.data_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.login_name_edit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_name_edit.setFont(font)
        self.login_name_edit.setClearButtonEnabled(True)
        self.login_name_edit.setObjectName("login_name_edit")
        self.data_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.login_name_edit)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.data_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.login_edit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_edit.setFont(font)
        self.login_edit.setClearButtonEnabled(True)
        self.login_edit.setObjectName("login_edit")
        self.data_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.login_edit)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.data_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.verticalLayout.addLayout(self.data_layout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sudmit_edit = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sudmit_edit.setFont(font)
        self.sudmit_edit.setObjectName("sudmit_edit")
        self.horizontalLayout_3.addWidget(self.sudmit_edit)
        self.cancel_edit = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_edit.setFont(font)
        self.cancel_edit.setObjectName("cancel_edit")
        self.horizontalLayout_3.addWidget(self.cancel_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hide_tool_button.setText(_translate("Form", "Close Editing"))
        self.label.setText(_translate("Form", "Login Name"))
        self.label_2.setText(_translate("Form", "Login"))
        self.label_3.setText(_translate("Form", "Password"))
        self.sudmit_edit.setText(_translate("Form", "Submit"))
        self.cancel_edit.setText(_translate("Form", "Cancel"))
