# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui/edit_section.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 352)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(900, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.hide_tool_button = QtWidgets.QToolButton(Form)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.hide_tool_button.setFont(font)
        self.hide_tool_button.setStyleSheet("QToolButton {\n"
"    border-radius: 8px;\n"
"    border: 2px solid orange;\n"
"      color: black;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      font-size: 20px;\n"
"      margin: 0px 0px;\n"
"}")
        self.hide_tool_button.setIconSize(QtCore.QSize(18, 18))
        self.hide_tool_button.setObjectName("hide_tool_button")
        self.horizontalLayout_5.addWidget(self.hide_tool_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.data_layout = QtWidgets.QFormLayout()
        self.data_layout.setObjectName("data_layout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.data_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.login_name = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_name.setFont(font)
        self.login_name.setClearButtonEnabled(True)
        self.login_name.setObjectName("login_name")
        self.data_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.login_name)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.data_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.login = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login.setFont(font)
        self.login.setClearButtonEnabled(True)
        self.login.setObjectName("login")
        self.data_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.login)
        self.verticalLayout.addLayout(self.data_layout)
        self.scroll_tag_area = QtWidgets.QScrollArea(Form)
        self.scroll_tag_area.setWidgetResizable(True)
        self.scroll_tag_area.setObjectName("scroll_tag_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 406, 169))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tag_widget = TagWidget(self.scrollAreaWidgetContents)
        self.tag_widget.setGeometry(QtCore.QRect(140, 30, 120, 80))
        self.tag_widget.setObjectName("tag_widget")
        self.scroll_tag_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scroll_tag_area)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.sudmit_editing = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sudmit_editing.setFont(font)
        self.sudmit_editing.setObjectName("sudmit_editing")
        self.horizontalLayout_3.addWidget(self.sudmit_editing)
        spacerItem2 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hide_tool_button.setText(_translate("Form", "x"))
        self.label.setText(_translate("Form", "Login Name"))
        self.label_2.setText(_translate("Form", "Login"))
        self.sudmit_editing.setText(_translate("Form", "Submit"))
from tags_widget import TagWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
