# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui/greeting_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_greeting_window(object):
    def setupUi(self, greeting_window):
        greeting_window.setObjectName("greeting_window")
        greeting_window.resize(420, 470)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(greeting_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_layout = QtWidgets.QVBoxLayout()
        self.image_layout.setObjectName("image_layout")
        self.label = QtWidgets.QLabel(greeting_window)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(400, 400))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("window_ui/../images/download.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.image_layout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.image_layout)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem)
        self.sign_in_button = QtWidgets.QPushButton(greeting_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sign_in_button.sizePolicy().hasHeightForWidth())
        self.sign_in_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.sign_in_button.setFont(font)
        self.sign_in_button.setStyleSheet("QPushButton{\n"
" width: 80px;\n"
"  height: 40px;\n"
"border: 1px solid black;\n"
"  border-radius: 12px;\n"
"}")
        self.sign_in_button.setObjectName("sign_in_button")
        self.buttons_layout.addWidget(self.sign_in_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem1)
        self.sign_up_button = QtWidgets.QPushButton(greeting_window)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sign_up_button.setFont(font)
        self.sign_up_button.setStyleSheet("QPushButton{\n"
" width: 80px;\n"
"  height: 40px;\n"
"border: 1px solid black;\n"
"  border-radius: 12px;\n"
"}")
        self.sign_up_button.setObjectName("sign_up_button")
        self.buttons_layout.addWidget(self.sign_up_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.buttons_layout)

        self.retranslateUi(greeting_window)
        QtCore.QMetaObject.connectSlotsByName(greeting_window)

    def retranslateUi(self, greeting_window):
        _translate = QtCore.QCoreApplication.translate
        greeting_window.setWindowTitle(_translate("greeting_window", "Hello"))
        self.sign_in_button.setText(_translate("greeting_window", "Sign Up"))
        self.sign_up_button.setText(_translate("greeting_window", "Sign In"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    greeting_window = QtWidgets.QDialog()
    ui = Ui_greeting_window()
    ui.setupUi(greeting_window)
    greeting_window.show()
    sys.exit(app.exec_())
