# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui/import_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_import_window(object):
    def setupUi(self, import_window):
        import_window.setObjectName("import_window")
        import_window.resize(244, 149)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(import_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.warning_label = QtWidgets.QLabel(import_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.warning_label.setFont(font)
        self.warning_label.setObjectName("warning_label")
        self.verticalLayout.addWidget(self.warning_label)
        self.combo_box = QtWidgets.QComboBox(import_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.combo_box.setFont(font)
        self.combo_box.setObjectName("combo_box")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.verticalLayout.addWidget(self.combo_box)
        self.all_records = QtWidgets.QCheckBox(import_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.all_records.setFont(font)
        self.all_records.setObjectName("all_records")
        self.verticalLayout.addWidget(self.all_records)
        self.submit_button = QtWidgets.QPushButton(import_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.verticalLayout.addWidget(self.submit_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(import_window)
        QtCore.QMetaObject.connectSlotsByName(import_window)

    def retranslateUi(self, import_window):
        _translate = QtCore.QCoreApplication.translate
        import_window.setWindowTitle(_translate("import_window", "Dialog"))
        self.warning_label.setText(_translate("import_window", "TextLabel"))
        self.combo_box.setItemText(0, _translate("import_window", "Replace with imported login"))
        self.combo_box.setItemText(1, _translate("import_window", "Add with new name"))
        self.combo_box.setItemText(2, _translate("import_window", "Do nothing"))
        self.all_records.setText(_translate("import_window", "For all conflict records"))
        self.submit_button.setText(_translate("import_window", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    import_window = QtWidgets.QDialog()
    ui = Ui_import_window()
    ui.setupUi(import_window)
    import_window.show()
    sys.exit(app.exec_())
