# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_dialog(object):
    def setupUi(self, login_dialog):
        login_dialog.setObjectName("login_dialog")
        login_dialog.resize(368, 232)
        font = QtGui.QFont()
        font.setPointSize(12)
        login_dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(login_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.photo_frame = QtWidgets.QFrame(login_dialog)
        self.photo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.photo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.photo_frame.setObjectName("photo_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.photo_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exit_user_button = QtWidgets.QToolButton(self.photo_frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("window_ui/../images/exit_door.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_user_button.setIcon(icon)
        self.exit_user_button.setIconSize(QtCore.QSize(20, 20))
        self.exit_user_button.setObjectName("exit_user_button")
        self.horizontalLayout_3.addWidget(self.exit_user_button)
        spacerItem = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.user_photo_button = QtWidgets.QToolButton(self.photo_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.user_photo_button.setFont(font)
        self.user_photo_button.setStyleSheet("QToolButton{\n"
"background-color: #D0D3D4;\n"
"border-radius:30%;\n"
"color: black;\n"
"padding: 20px;\n"
"margin: 4px 2px;\n"
"}")
        self.user_photo_button.setIconSize(QtCore.QSize(16, 16))
        self.user_photo_button.setObjectName("user_photo_button")
        self.horizontalLayout_2.addWidget(self.user_photo_button)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.edit_user_button = QtWidgets.QToolButton(self.photo_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_user_button.sizePolicy().hasHeightForWidth())
        self.edit_user_button.setSizePolicy(sizePolicy)
        self.edit_user_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.edit_user_button.setStyleSheet("QToolButton:hover{\n"
"    background-color:grey;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("window_ui/../images/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_user_button.setIcon(icon1)
        self.edit_user_button.setIconSize(QtCore.QSize(20, 20))
        self.edit_user_button.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.edit_user_button.setObjectName("edit_user_button")
        self.horizontalLayout.addWidget(self.edit_user_button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.photo_frame)
        self.frame = QtWidgets.QFrame(login_dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.password_layout = QtWidgets.QFormLayout()
        self.password_layout.setObjectName("password_layout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.password_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.user_name = QtWidgets.QLineEdit(self.frame)
        self.user_name.setMaxLength(16)
        self.user_name.setObjectName("user_name")
        self.password_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user_name)
        self.verticalLayout_4.addLayout(self.password_layout)
        self.verticalLayout.addWidget(self.frame)
        self.submit_login = QtWidgets.QPushButton(login_dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submit_login.setFont(font)
        self.submit_login.setToolTipDuration(0)
        self.submit_login.setObjectName("submit_login")
        self.verticalLayout.addWidget(self.submit_login)

        self.retranslateUi(login_dialog)
        QtCore.QMetaObject.connectSlotsByName(login_dialog)

    def retranslateUi(self, login_dialog):
        _translate = QtCore.QCoreApplication.translate
        login_dialog.setWindowTitle(_translate("login_dialog", "Login"))
        self.exit_user_button.setText(_translate("login_dialog", "..."))
        self.user_photo_button.setText(_translate("login_dialog", "U"))
        self.edit_user_button.setText(_translate("login_dialog", "..."))
        self.label.setText(_translate("login_dialog", "Name"))
        self.submit_login.setText(_translate("login_dialog", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_dialog = QtWidgets.QDialog()
    ui = Ui_login_dialog()
    ui.setupUi(login_dialog)
    login_dialog.show()
    sys.exit(app.exec_())
