# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(835, 387)
        self.main_widget = QtWidgets.QWidget(main_window)
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_info_button = QtWidgets.QToolButton(self.main_widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.user_info_button.setFont(font)
        self.user_info_button.setStyleSheet("QToolButton{\n"
"background-color: #D0D3D4;\n"
"border-radius:20%;\n"
"color: black;\n"
"padding: 15px;\n"
"margin: 4px 2px;\n"
"}")
        self.user_info_button.setObjectName("user_info_button")
        self.verticalLayout.addWidget(self.user_info_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logins_list = QtWidgets.QListWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logins_list.sizePolicy().hasHeightForWidth())
        self.logins_list.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logins_list.setFont(font)
        self.logins_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logins_list.setViewMode(QtWidgets.QListView.ListMode)
        self.logins_list.setObjectName("logins_list")
        self.horizontalLayout.addWidget(self.logins_list)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(400, 400))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayout = QtWidgets.QFormLayout(self.page)
        self.formLayout.setObjectName("formLayout")
        self.edit_section = EditSection(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_section.sizePolicy().hasHeightForWidth())
        self.edit_section.setSizePolicy(sizePolicy)
        self.edit_section.setMinimumSize(QtCore.QSize(100, 100))
        self.edit_section.setObjectName("edit_section")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.edit_section)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        main_window.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 25))
        self.menubar.setObjectName("menubar")
        self.menu_new = QtWidgets.QMenu(self.menubar)
        self.menu_new.setObjectName("menu_new")
        self.menuExport_Import = QtWidgets.QMenu(self.menu_new)
        self.menuExport_Import.setObjectName("menuExport_Import")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.action_new_password = QtWidgets.QAction(main_window)
        self.action_new_password.setObjectName("action_new_password")
        self.actionInformation = QtWidgets.QAction(main_window)
        self.actionInformation.setObjectName("actionInformation")
        self.actionChange_Theme = QtWidgets.QAction(main_window)
        self.actionChange_Theme.setObjectName("actionChange_Theme")
        self.action_delete_user = QtWidgets.QAction(main_window)
        self.action_delete_user.setObjectName("action_delete_user")
        self.action_pass_import = QtWidgets.QAction(main_window)
        self.action_pass_import.setObjectName("action_pass_import")
        self.action_pass_export = QtWidgets.QAction(main_window)
        self.action_pass_export.setObjectName("action_pass_export")
        self.menuExport_Import.addAction(self.action_pass_import)
        self.menuExport_Import.addAction(self.action_pass_export)
        self.menu_new.addAction(self.action_new_password)
        self.menu_new.addAction(self.menuExport_Import.menuAction())
        self.menu_new.addAction(self.action_delete_user)
        self.menuPreferences.addAction(self.actionChange_Theme)
        self.menuHelp.addAction(self.actionInformation)
        self.menubar.addAction(self.menu_new.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(main_window)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Password Manager"))
        self.user_info_button.setText(_translate("main_window", "U"))
        self.menu_new.setTitle(_translate("main_window", "New.."))
        self.menuExport_Import.setTitle(_translate("main_window", "Import/Export.."))
        self.menuPreferences.setTitle(_translate("main_window", "Preferences"))
        self.menuHelp.setTitle(_translate("main_window", "Help"))
        self.action_new_password.setText(_translate("main_window", "New Password"))
        self.actionInformation.setText(_translate("main_window", "Information"))
        self.actionChange_Theme.setText(_translate("main_window", "Change Theme"))
        self.action_delete_user.setText(_translate("main_window", "Delete Account"))
        self.action_pass_import.setText(_translate("main_window", "Import"))
        self.action_pass_export.setText(_translate("main_window", "Export"))
from edit_section import EditSection


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
