# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui/new_record.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_record_dialog(object):
    def setupUi(self, new_record_dialog):
        new_record_dialog.setObjectName("new_record_dialog")
        new_record_dialog.resize(347, 403)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("window_ui/../images/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        new_record_dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(new_record_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_login_layout = QtWidgets.QFormLayout()
        self.new_login_layout.setObjectName("new_login_layout")
        self.label_name = QtWidgets.QLabel(new_record_dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.new_login_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.new_name = QtWidgets.QLineEdit(new_record_dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_name.setFont(font)
        self.new_name.setObjectName("new_name")
        self.new_login_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.new_name)
        self.label_login = QtWidgets.QLabel(new_record_dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_login.setFont(font)
        self.label_login.setObjectName("label_login")
        self.new_login_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_login)
        self.new_login = QtWidgets.QLineEdit(new_record_dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_login.setFont(font)
        self.new_login.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.new_login.setObjectName("new_login")
        self.new_login_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.new_login)
        self.verticalLayout.addLayout(self.new_login_layout)
        self.scroll_area = QtWidgets.QScrollArea(new_record_dialog)
        self.scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 329, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tag_widget = TagWidget(self.scrollAreaWidgetContents)
        self.tag_widget.setGeometry(QtCore.QRect(110, 100, 120, 80))
        self.tag_widget.setObjectName("tag_widget")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scroll_area)
        self.submit_record = QtWidgets.QPushButton(new_record_dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submit_record.setFont(font)
        self.submit_record.setObjectName("submit_record")
        self.verticalLayout.addWidget(self.submit_record)

        self.retranslateUi(new_record_dialog)
        QtCore.QMetaObject.connectSlotsByName(new_record_dialog)

    def retranslateUi(self, new_record_dialog):
        _translate = QtCore.QCoreApplication.translate
        new_record_dialog.setWindowTitle(_translate("new_record_dialog", "Add New Record"))
        self.label_name.setText(_translate("new_record_dialog", "Name"))
        self.label_login.setText(_translate("new_record_dialog", "Login"))
        self.submit_record.setText(_translate("new_record_dialog", "Submit"))
from tags_widget import TagWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_record_dialog = QtWidgets.QDialog()
    ui = Ui_new_record_dialog()
    ui.setupUi(new_record_dialog)
    new_record_dialog.show()
    sys.exit(app.exec_())
