# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui/new_name_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_name_window(object):
    def setupUi(self, new_name_window):
        new_name_window.setObjectName("new_name_window")
        new_name_window.resize(256, 94)
        self.verticalLayout = QtWidgets.QVBoxLayout(new_name_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(new_name_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.new_name = QtWidgets.QLineEdit(new_name_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.new_name.setFont(font)
        self.new_name.setMaxLength(16)
        self.new_name.setObjectName("new_name")
        self.horizontalLayout.addWidget(self.new_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.submit_button = QtWidgets.QPushButton(new_name_window)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.verticalLayout.addWidget(self.submit_button)

        self.retranslateUi(new_name_window)
        QtCore.QMetaObject.connectSlotsByName(new_name_window)

    def retranslateUi(self, new_name_window):
        _translate = QtCore.QCoreApplication.translate
        new_name_window.setWindowTitle(_translate("new_name_window", "New Record Name"))
        self.label.setText(_translate("new_name_window", "New Name"))
        self.submit_button.setText(_translate("new_name_window", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_name_window = QtWidgets.QDialog()
    ui = Ui_new_name_window()
    ui.setupUi(new_name_window)
    new_name_window.show()
    sys.exit(app.exec_())
