# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui/tags_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tags_window(object):
    def setupUi(self, tags_window):
        tags_window.setObjectName("tags_window")
        tags_window.resize(333, 148)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(tags_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(tags_window)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.tag_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tag_label.setFont(font)
        self.tag_label.setObjectName("tag_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tag_label)
        self.tag_name = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tag_name.setFont(font)
        self.tag_name.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tag_name.setInputMethodHints(QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhPreferLatin)
        self.tag_name.setMaxLength(14)
        self.tag_name.setClearButtonEnabled(True)
        self.tag_name.setObjectName("tag_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tag_name)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(tags_window)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.colour_layout = QtWidgets.QGridLayout()
        self.colour_layout.setObjectName("colour_layout")
        self.horizontalLayout_3.addLayout(self.colour_layout)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.tag_submit = QtWidgets.QPushButton(tags_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tag_submit.setFont(font)
        self.tag_submit.setObjectName("tag_submit")
        self.verticalLayout_2.addWidget(self.tag_submit)

        self.retranslateUi(tags_window)
        QtCore.QMetaObject.connectSlotsByName(tags_window)

    def retranslateUi(self, tags_window):
        _translate = QtCore.QCoreApplication.translate
        tags_window.setWindowTitle(_translate("tags_window", "Add Tag"))
        self.tag_label.setText(_translate("tags_window", "Tag Name"))
        self.tag_submit.setText(_translate("tags_window", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tags_window = QtWidgets.QDialog()
    ui = Ui_tags_window()
    ui.setupUi(tags_window)
    tags_window.show()
    sys.exit(app.exec_())
